import "@/styles/globals.css";
import type { Metadata } from "next";
import Header from "@/components/layout/header/page";
import Nav from "@/components/layout/nav/page";

export const metadata: Metadata = {
  title: "Qeeta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Header />
        <Nav />
        {children}
      </body>
    </html>
  );
}
